import { ICategoria } from '../modules/categorias/interface/ categoria.interface';

export const dataSourcesCategorias: ICategoria[] = [
  { _id: "1", nome: "Eletrônicos" },
  { _id: "2", nome: "Moda" },
  { _id: "3", nome: "Casa e Jardim" },
  { _id: "4", nome: "Esportes" },
  { _id: "5", nome: "Automotivo" },
  { _id: "6", nome: "Livros" },
  { _id: "7", nome: "Saúde e Beleza" },
  { _id: "8", nome: "Jogos" },
  { _id: "9", nome: "Ferramentas" },
  { _id: "10", nome: "Brinquedos" },
  { _id: "11", nome: "Alimentos e Bebidas" },
  { _id: "12", nome: "Animais de Estimação" },
  { _id: "13", nome: "Móveis" },
  { _id: "14", nome: "Instrumentos Musicais" },
  { _id: "15", nome: "Viagens" },
  { _id: "16", nome: "Arte e Artesanato" },
  { _id: "17", nome: "Telefonia" },
  { _id: "18", nome: "Informática" },
  { _id: "19", nome: "Bebês" },
  { _id: "20", nome: "Relógios" },
  { _id: "21", nome: "Joias" },
  { _id: "22", nome: "Decoração" },
  { _id: "23", nome: "Filmes e Séries" },
  { _id: "24", nome: "Cosméticos" },
  { _id: "25", nome: "Eletrodomésticos" },
  { _id: "26", nome: "Fitness" },
  { _id: "27", nome: "Camping e Outdoor" },
  { _id: "28", nome: "Instrumentos Científicos" },
  { _id: "29", nome: "Roupas Íntimas" },
  { _id: "30", nome: "Produtos de Limpeza" },
  { _id: "31", nome: "Plantas e Flores" },
  { _id: "32", nome: "Armas e Acessórios" },
  { _id: "33", nome: "Pesca" },
  { _id: "34", nome: "Fotografia" },
  { _id: "35", nome: "História e Cultura" },
  { _id: "36", nome: "Acessórios para Veículos" },
  { _id: "37", nome: "Antiguidades" },
  { _id: "38", nome: "Dança e Ballet" },
  { _id: "39", nome: "Jardinagem" },
  { _id: "40", nome: "Bricolagem" },
  { _id: "41", nome: "Medicina Alternativa" },
  { _id: "42", nome: "Papelaria" },
  { _id: "43", nome: "Astronomia" },
  { _id: "44", nome: "Coleções" },
  { _id: "45", nome: "Engenharia" },
  { _id: "46", nome: "Biologia" },
  { _id: "47", nome: "Geologia" },
  { _id: "48", nome: "Economia" },
  { _id: "49", nome: "Marketing" },
  { _id: "50", nome: "Psicologia" }
]